export default [
    {
        id: 1,
        boundsIndex: 72,
        capitol: [1483, 235],
        name: 'Tamblair',
        startingFactionId: 2,
    },
    {
        id: 2,
        boundsIndex: 71,
        capitol: [1572, 317],
        name: 'Kinforth',
        startingFactionId: 2,
    },
    {
        id: 3,
        boundsIndex: 70,
        capitol: [1507, 348],
        name: 'Oaxley',
        startingFactionId: 2,
    },
    {
        id: 4,
        boundsIndex: 69,
        capitol: [1513, 549],
        name: 'Utentana',
        startingFactionId: 2,
    },
    {
        id: 5,
        boundsIndex: 30,
        capitol: [1377, 235],
        name: 'Cusichaca',
        startingFactionId: 2,
    },
    {
        id: 6,
        boundsIndex: 31,
        capitol: [1271, 419],
        name: 'Hongshi Coast',
        startingFactionId: 2,
    },
    {
        id: 55,
        boundsIndex: 33,
        capitol: [1238, 588],
        name: 'Yunin',
        startingFactionId: 0,
    },
    {
        id: 56,
        boundsIndex: 60,
        capitol: [1336, 677],
        name: 'Paritus',
        startingFactionId: 0,
    },
    {
        id: 8,
        boundsIndex: 61,
        capitol: [1460, 611],
        name: 'Hanat',
        startingFactionId: 2,
    },
    {
        id: 7,
        boundsIndex: 68,
        capitol: [1548, 749],
        name: 'Qinqaachi',
        startingFactionId: 2,
    },
    {
        id: 9,
        boundsIndex: 67,
        capitol: [1512, 885],
        name: 'Ulavaar',
        startingFactionId: 2,
    },
    {
        id: 53,
        boundsIndex: 62,
        capitol: [1321, 875],
        name: 'Anvala',
        startingFactionId: 1,
    },
    {
        id: 57,
        boundsIndex: 59,
        capitol: [1239, 840],
        name: 'Virna',
        startingFactionId: 0,
    },
    {
        id: 52,
        boundsIndex: 63,
        capitol: [1300, 984],
        name: 'Urhal',
        startingFactionId: 1,
    },
    {
        id: 54,
        boundsIndex: 66,
        capitol: [1445, 1078],
        name: 'Northlake',
        startingFactionId: 1,
    },
    {
        id: 47,
        boundsIndex: 64,
        capitol: [1278, 1148],
        name: 'Lord\'s Leap',
        startingFactionId: 1,
    },
    {
        id: 51,
        boundsIndex: 55,
        capitol: [1250, 1080],
        name: 'Skyend',
        startingFactionId: 1,
    },
    {
        id: 50,
        boundsIndex: 54,
        capitol: [1229, 1150],
        name: 'Ravenrock',
        startingFactionId: 1,
    },
    {
        id: 46,
        boundsIndex: 65,
        capitol: [1430, 1221],
        name: 'Glowwater',
        startingFactionId: 1,
    },
    {
        id: 58,
        boundsIndex: 56,
        capitol: [1162, 1006],
        name: 'Faberia',
        startingFactionId: 0,
    },
    {
        id: 59,
        boundsIndex: 45,
        capitol: [1077, 1190],
        name: 'Aspara',
        startingFactionId: 0,
    },
    {
        id: 70,
        boundsIndex: 57,
        capitol: [1135, 888],
        name: 'Bannen\'s Rest',
        startingFactionId: 0,
    },
    {
        id: 69,
        boundsIndex: 58,
        capitol: [1180, 766],
        name: 'Fallow',
        startingFactionId: 0,
    },
    {
        id: 73,
        boundsIndex: 36,
        capitol: [1077, 799],
        name: 'Cathedral',
        startingFactionId: 0,
    },
    {
        id: 68,
        boundsIndex: 34,
        capitol: [1105, 695],
        name: 'Aleston',
        startingFactionId: 0,
    },
    {
        id: 67,
        boundsIndex: 32,
        capitol: [1141, 604],
        name: 'Suna',
        startingFactionId: 0,
    },
    {
        id: 10,
        boundsIndex: 29,
        capitol: [1147, 394],
        name: 'Jingshan',
        startingFactionId: 6,
    },
    {
        id: 13,
        boundsIndex: 23,
        capitol: [991, 294],
        name: 'Changning',
        startingFactionId: 6,
    },
    {
        id: 12,
        boundsIndex: 24,
        capitol: [1031, 400],
        name: 'Wu Tower',
        startingFactionId: 6,
    },
    {
        id: 11,
        boundsIndex: 28,
        capitol: [1061, 511],
        name: 'Qinjuru',
        startingFactionId: 6,
    },
    {
        id: 66,
        boundsIndex: 27,
        capitol: [1009, 576],
        name: 'Saltpan',
        startingFactionId: 0,
    },
    {
        id: 65,
        boundsIndex: 35,
        capitol: [1026, 685],
        name: 'Oblivion Pass',
        startingFactionId: 0,
    },
    {
        id: 72,
        boundsIndex: 37,
        capitol: [1012, 747],
        name: 'Garrow',
        startingFactionId: 0,
    },
    {
        id: 71,
        boundsIndex: 40,
        capitol: [1019, 871],
        name: 'Sunder',
        startingFactionId: 0,
    },
    {
        id: 60,
        boundsIndex: 41,
        capitol: [1016, 1021],
        name: 'Lookout',
        startingFactionId: 0,
    },
    {
        id: 37,
        boundsIndex: 44,
        capitol: [978, 1152],
        name: 'Ballast',
        startingFactionId: 3
    },
    {
        id: 28,
        boundsIndex: 43,
        capitol: [886, 1218],
        name: 'Troydon',
        startingFactionId: 4,
    },
    {
        id: 61,
        boundsIndex: 42,
        capitol: [960, 1008],
        name: 'Boomtown',
        startingFactionId: 0,
    },
    {
        id: 62,
        boundsIndex: 39,
        capitol: [924, 936],
        name: 'Jackson Hole',
        startingFactionId: 0,
    },
    {
        id: 63,
        boundsIndex: 38,
        capitol: [769, 908],
        name: 'Albys',
        startingFactionId: 0,
    },
    {
        id: 64,
        boundsIndex: 26,
        capitol: [901, 596],
        name: 'Orrington',
        startingFactionId: 0,
    },
    {
        id: 14,
        boundsIndex: 25,
        capitol: [876, 486],
        name: 'Sanctuary',
        startingFactionId: 6,
    },
    {
        id: 16,
        boundsIndex: 21,
        capitol: [853, 359],
        name: 'Yao Ling Pass',
        startingFactionId: 6,
    },
    {
        id: 15,
        boundsIndex: 22,
        capitol: [894, 235],
        name: 'Lu Tower',
        startingFactionId: 6,
    },
    {
        id: 17,
        boundsIndex: 20,
        capitol: [812, 260],
        name: 'Bai Hua Hills',
        startingFactionId: 6,
    },
    {
        id: 18,
        boundsIndex: 19,
        capitol: [782, 466],
        name: 'Dragontown',
        startingFactionId: 6,
    },
    {
        id: 22,
        boundsIndex: 18,
        capitol: [798, 645],
        name: 'Faron',
        startingFactionId: 5,
    },
    {
        id: 25,
        boundsIndex: 17,
        capitol: [605, 578],
        name: 'Landmark',
        startingFactionId: 5,
    },
    {
        id: 21,
        boundsIndex: 16,
        capitol: [678, 430],
        name: 'Naufrage',
        startingFactionId: 5,
    },
    {
        id: 20,
        boundsIndex: 15,
        capitol: [692, 348],
        name: 'Sabbia',
        startingFactionId: 5,
    },
    {
        id: 19,
        boundsIndex: 14,
        capitol: [704, 211],
        name: 'Flyaway',
        startingFactionId: 5,
    },
    {
        id: 23,
        boundsIndex: 13,
        capitol: [584, 306],
        name: 'Canon',
        startingFactionId: 5,
    },
    {
        id: 24,
        boundsIndex: 12,
        capitol: [505, 382],
        name: 'Alleron',
        startingFactionId: 5,
    },
    {
        id: 26,
        boundsIndex: 11,
        capitol: [482, 578],
        name: 'Caldera',
        startingFactionId: 5,
    },
    {
        id: 27,
        boundsIndex: 10,
        capitol: [462, 743],
        name: 'Kire',
        startingFactionId: 5,
    },
    {
        id: 29,
        boundsIndex: 9,
        capitol: [485, 885],
        name: 'Sabakumura',
        startingFactionId: 4,
    },
    {
        id: 31,
        boundsIndex: 8,
        capitol: [491, 1020],
        name: 'Selogorod',
        startingFactionId: 4,
    },
    {
        id: 30,
        boundsIndex: 7,
        capitol: [562, 1029],
        name: 'Orlevsela',
        startingFactionId: 4,
    },
    {
        id: 32,
        boundsIndex: 6,
        capitol: [631, 1103],
        name: 'Starostrog',
        startingFactionId: 4,
    },
    {
        id: 33,
        boundsIndex: 5,
        capitol: [464, 1142],
        name: 'Vyshtorg',
        startingFactionId: 4,
    },
    {
        id: 34,
        boundsIndex: 4,
        capitol: [680, 1225],
        name: 'Vama Rea',
        startingFactionId: 4,
    },
    {
        id: 35,
        boundsIndex: 3,
        capitol: [552, 1391],
        name: 'Mor Mare',
        startingFactionId: 4,
    },
    {
        id: 36,
        boundsIndex: 2,
        capitol: [681, 1590],
        name: 'Andelata',
        startingFactionId: 4,
    },
    {
        id: 45,
        boundsIndex: 1,
        capitol: [753, 1638],
        name: 'Lirodunum',
        startingFactionId: 3,
    },
    {
        id: 44,
        boundsIndex: 0,
        capitol: [808, 1781],
        name: 'Beldusios',
        startingFactionId: 3,
    },
    {
        id: 43,
        boundsIndex: 46,
        capitol: [970, 1761],
        name: 'Allonia',
        startingFactionId: 3,
    },
    {
        id: 42,
        boundsIndex: 47,
        capitol: [864, 1633],
        name: 'Lutessa',
        startingFactionId: 3,
    },
    {
        id: 41,
        boundsIndex: 48,
        capitol: [1059, 1602],
        name: 'Averna',
        startingFactionId: 3,
    },
    {
        id: 40,
        boundsIndex: 49,
        capitol: [1170, 1579],
        name: 'Anthos',
        startingFactionId: 3,
    },
    {
        id: 39,
        boundsIndex: 50,
        capitol: [1046, 1487],
        name: 'Lascus',
        startingFactionId: 3,
    },
    {
        id: 38,
        boundsIndex: 51,
        capitol: [1151, 1409],
        name: 'Itonia',
        startingFactionId: 3,
    },
    {
        id: 49,
        boundsIndex: 52,
        capitol: [1278, 1326],
        name: 'Serpent\'s Point',
        startingFactionId: 1,
    },
    {
        id: 48,
        boundsIndex: 53,
        capitol: [1228, 1284],
        name: 'Blackcliff',
        startingFactionId: 1,
    }
]